bin/env_variables_all.txt, src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
=> For updating properties and removed duplicate

.gitignore, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2350
https://tools.hmcts.net/jira/browse/RET-2351
https://tools.hmcts.net/jira/browse/RET-2352
https://tools.hmcts.net/jira/browse/RET-2353
https://tools.hmcts.net/jira/browse/RET-2354
https://tools.hmcts.net/jira/browse/RET-2355
ReviewReferralJudiciary & ReviewReferralLegalOps
```
[ ] Yes
[x] No
```
=> RET-2350: ReviewReferralJudiciary & ReviewReferralLegalOps

src/functionalTest/resources/scenarios/employment/ET-RET-2373-ListServeClaim-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2373
https://tools.hmcts.net/jira/browse/RET-2374
https://tools.hmcts.net/jira/browse/RET-2375
```
[ ] Yes
[x ] No
```
=>  RET-2373 add ListServeClaim

src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2386
https://tools.hmcts.net/jira/browse/RET-2388
https://tools.hmcts.net/jira/browse/RET-2389
This story deals with auto cancellation of "ReviewReferralResponseJudiciary" following closure of a case
```
[ ] Yes
[x] No
```
=> RET-2386-ReviewReferralResponseJudiciary

src/functionalTest/resources/scenarios/employment/ET-RET-2370-SendEt1Notification-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2370
https://tools.hmcts.net/jira/browse/RET-2371
https://tools.hmcts.net/jira/browse/RET-2372
RET-2370: Create “SendEt1Notification” Task for Admin
```
[ ] Yes
[x] No
```
=> RET-2370: Create “SendEt1Notification” Task for Admin

src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-shouldCreateTask.json
No JIRA
Quick Bug Fixes
```
[ ] Yes
[x] No
```
=> RET-2379-2383: Functional Test fixes

Dockerfile, build.gradle, charts/et-wa-post-deployment-ft-tests/Chart.yaml, charts/et-wa-post-deployment-ft-tests/values.yaml, lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/RET-3726
Upgrade project to Java 17
```
[ ] Yes
[x] No
```
=> RET-3726: Java 17

src/functionalTest/resources/scenarios/employment/ET-RET-2450-IssueJudgment-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2450
https://tools.hmcts.net/jira/browse/RET-2451
This story deals with auto creation of the "IssueJudgment" task following referral from a Judge 
```
[ ] Yes
[x] No
```
=> RET-2450-IssueJudgment

Jenkinsfile_CNP, src/functionalTest/resources/scenarios/employment/ET-RET-2432-CompleteInitialConsideration-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2432
https://tools.hmcts.net/jira/browse/RET-2433
https://tools.hmcts.net/jira/browse/RET-2434
This story deals with auto creation of "CompleteInitialConsideration" task following a referral from an Admin
```
[ ] Yes
[x] No
=> RET-2432-CompleteInitialConsideration

src/functionalTest/resources/scenarios/employment/ET-RET-2403-SendEt3Notification-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2403
https://tools.hmcts.net/jira/browse/RET-2404
https://tools.hmcts.net/jira/browse/RET-2405
This story deals with auto creation of "SendEt3Notification" task following acceptance/rejection of a case 
```
[ ] Yes
[x] No
```
=> RET-2403 send et3 notification

src/functionalTest/resources/scenarios/employment/ET-RET-3188a-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188b-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188c-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188d-ContactTribunalWithanApplication-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-3188
https://tools.hmcts.net/jira/browse/RET-3189
https://tools.hmcts.net/jira/browse/RET-3190
```
[ ] Yes
[ ] No
```
=> test case added

src/functionalTest/resources/scenarios/employment/ET-RET-2432-CompleteInitialConsideration-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2403
https://tools.hmcts.net/jira/browse/RET-2432
Update Functional Test 
```
[ ] Yes
[x] No
```
=> RET-2432: Functional Test update

src/functionalTest/resources/scenarios/employment/ET-RET-2344-Et1Vetting-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2376-Et3Processing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2403-SendEt3Notification-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2432-CompleteInitialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2438-IssuePostHearingDirection-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444a-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444b-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2450-IssueJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188a-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188b-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188c-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188d-ContactTribunalWithanApplication-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-3828
Case Name fix
```
[ ] Yes
[x] No
```
=> Ret 3828 - Case Name Fixes

src/functionalTest/resources/scenarios/employment/ET-RET-2501-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501a-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501b-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501c-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501d-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188a-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188b-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188c-ContactTribunalWithanApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188d-ContactTribunalWithanApplication-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2501
SUBMIT_CLAIMANT_TSE & respondentTSE done
```
[ ] Yes
[x] No
```
=> RET 2501 Create "AmendPartyDetails" Task for Admin

src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2438-IssuePostHearingDirection-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444a-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2450-IssueJudgment-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2347
```
[ ] Yes
[ ] No
```
=> RET-4056: Refactor Referrals

src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501a-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501b-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501c-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501d-AmendPartyDetails-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4244
AmendPartyDetails -> AmendRespondentDetails and AmendClaimantDetails)
```
[ ] Yes
[x] No
```
=> RET-4244: Different Taskid

src/functionalTest/resources/scenarios/employment/ET-RET-2432-CompleteInitialConsideration-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-2432
Update CaseData for CompleteInitialConsideration
```
[ ] Yes
[x] No
```
=> RET-2432: Update respondentCollection for CompleteInitialConsideration

src/functionalTest/resources/scenarios/employment/ET-RET-2344-Et1Vetting-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2435a-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2435b-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2438-IssuePostHearingDirection-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2450-IssueJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3180a-AddAmendJurisdiction-taskReconfigure.json, src/functionalTest/resources/scenarios/employment/ET-RET-3180c-AddAmendHearing-taskReconfigure.json, src/functionalTest/resources/scenarios/employment/ET-RET-4096-CancelTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397a-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397b-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397c-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/WIP/TODO-RET-3180b-caseTransferDifferentCountry-taskReconfigure.json
https://tools.hmcts.net/jira/browse/RET-4014
```
[ ] Yes
[x] No
```
=> RET-4014: List A Hearing

src/functionalTest/resources/scenarios/employment/ET-RET-2435-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2435a-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2435b-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397a-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397b-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4397c-ListAHearing-shouldCreateTask.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> RET-2345 amending initial consideration- task to include additional data

src/functionalTest/resources/scenarios/employment/ET-RET-2435c-initialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4014a-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4014b-ListAHearing-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4014c-ListAHearing-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4016
https://tools.hmcts.net/jira/browse/RET-2435
Connect up RET-4016 & RET-2435
=> RET-4016: Connect up RET-4016 & RET-2435

src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501a-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501b-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501c-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2501d-AmendPartyDetails-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3182-WithdrawAllOrPartOfCase-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188a-ContactTribunalWithAnApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188b-ContactTribunalWithAnApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188c-ContactTribunalWithAnApplication-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3188d-ContactTribunalWithAnApplication-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4515
https://tools.hmcts.net/jira/browse/RET-4518
Update Next Steps on Task for Referrals and Applications
```
[ ] Yes
[x] No
```
=> RET-4515-4518: Update Next Steps

src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2347-ReviewReferralAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-NotUrgent-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4515
Add ReferralNumber to Referral Task Names
```
[ ] Yes
[x] No
```
=> RET-4515:  Add ReferralNumber to Referral Task Names

src/functionalTest/resources/scenarios/employment/ET-RET-3296-ReviewRule21Referral-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-3296
Rule21 DelayUntil
```
[ ] Yes
[x] No
```
=> RET-3296: Rule21 DelayUntil

src/functionalTest/resources/scenarios/employment/ET-RET-2376-Et3Processing-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4516
Change triggering event for Et3Processing
=> RET-4516: Change triggering event for Et3Processing

build.gradle, config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/employment/ET-RET-4517-Et3Processing-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4517
Add additional triggering event for Et3Processing
=> RET-4517: Add triggering event for Et3Processing

src/functionalTest/resources/scenarios/employment/ET-RET-2438-IssuePostHearingDirection-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444a-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2450-IssueJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-4095-CompleteTask.json
https://tools.hmcts.net/jira/browse/RET-4515
Some additional tests for Referrals and Applications
```
[ ] Yes
[x] No
```
=> RET-4515: Some additional tests

src/functionalTest/resources/scenarios/employment/ET-RET-2403-SendEt3Notification-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444b-DraftAndSignJudgment-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4784
Update for Draft & Sign Judgement
And update for Complete Initial Consideration
```
[ ] Yes
[x] No
```
=> RET-4784: Update for Draft And Sign Judgement

src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2350-ReviewReferralLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2353-ReviewReferralJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2383-ReviewReferralResponseLegalOps-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2386-ReviewReferralResponseJudiciary-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2403-SendEt3Notification-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2432-CompleteInitialConsideration-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444a-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-2444b-DraftAndSignJudgment-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/ET-RET-3296-ReviewRule21Referral-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-4838
Add Lead Judge as a Case Role
```
[ ] Yes
[x] No
```
=> RET-4838: Add Lead Judge as Case Role

src/functionalTest/resources/scenarios/employment/ET-RET-5010-ReviewECCResponse-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-5010
New Task for Review ECC Response
```
[ ] Yes
[x] No
```
=> RET-5010: Add Test for ReviewECCResponse

src/functionalTest/resources/scenarios/employment/ET-RET-2403-2432-SendEt3Notification-CompleteInitialConsideration-shouldCreateTask.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RET-5038
Add ECC clause
```
[ ] Yes
[x] No
```
=> RET-5038 - Add ECC clause

README.md, src/functionalTest/resources/scenarios/employment/ET-RET-2379-ReviewReferralResponseAdmin-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/multiples/ET-RET-5135-ReviewReferralLegalOpsMultiple-IsUrgent-shouldCreateTask.json, src/functionalTest/resources/scenarios/employment/multiples/ET-RET-5135-ReviewReferralLegalOpsMultiple-NotUrgent-shouldCreateTask.json, src/functionalTest/resources/templates/employment/ccd/minimal-multiple-case.json, src/functionalTest/resources/templates/employment/message/ccd-event-message.json
https://tools.hmcts.net/jira/browse/RET-5135
Create Task "MultiplesReviewReferralLegalOps" for Legal Caseworker (MUL WA)
```
[ ] Yes
[x] No
```
=> RET-5135: MultiplesReviewReferralLegalOps

src/functionalTest/resources/scenarios/employment/ET-RET-5233-Rule21-Referral-shouldCreateTask.json
https://tools.hmcts.net/jira/browse/RET-5233
```
[ ] Yes
[ ] No
```
=> Refactor Rule 21 creating draft and sign to review referral
